/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CarModelInput = IDL.Record({
  'name' : IDL.Text,
  'year' : IDL.Nat,
  'available' : IDL.Bool,
  'category' : IDL.Text,
});
export const CarModelId = IDL.Nat;
export const DealerLocationInput = IDL.Record({
  'city' : IDL.Text,
  'name' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const DealerLocationId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TestDriveInput = IDL.Record({
  'customerName' : IDL.Text,
  'customerPhone' : IDL.Text,
  'scheduledDate' : IDL.Text,
  'carModelId' : CarModelId,
  'notes' : IDL.Text,
  'dealerLocationId' : DealerLocationId,
});
export const TestDriveId = IDL.Nat;
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const DashboardStats = IDL.Record({
  'scheduled' : IDL.Nat,
  'total' : IDL.Nat,
  'cancelled' : IDL.Nat,
  'completed' : IDL.Nat,
  'inProgress' : IDL.Nat,
});
export const CarModel = IDL.Record({
  'id' : CarModelId,
  'name' : IDL.Text,
  'year' : IDL.Nat,
  'available' : IDL.Bool,
  'category' : IDL.Text,
});
export const DealerLocation = IDL.Record({
  'id' : DealerLocationId,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const TestDrive = IDL.Record({
  'id' : TestDriveId,
  'customerName' : IDL.Text,
  'status' : IDL.Variant({
    'scheduled' : IDL.Null,
    'cancelled' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  }),
  'customerPhone' : IDL.Text,
  'scheduledDate' : IDL.Text,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'carModelId' : CarModelId,
  'notes' : IDL.Text,
  'dealerLocationId' : DealerLocationId,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCarModel' : IDL.Func([CarModelInput], [CarModelId], []),
  'addDealerLocation' : IDL.Func([DealerLocationInput], [DealerLocationId], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bookTestDrive' : IDL.Func([TestDriveInput], [TestDriveId], []),
  'cancelTestDrive' : IDL.Func([TestDriveId], [], []),
  'deleteCarModel' : IDL.Func([CarModelId], [], []),
  'deleteDealerLocation' : IDL.Func([DealerLocationId], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listCarModels' : IDL.Func([], [IDL.Vec(CarModel)], ['query']),
  'listDealerLocations' : IDL.Func([], [IDL.Vec(DealerLocation)], ['query']),
  'listTestDrives' : IDL.Func([], [IDL.Vec(TestDrive)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'toggleCarModelAvailability' : IDL.Func([CarModelId], [], []),
  'updateTestDriveStatus' : IDL.Func(
      [
        TestDriveId,
        IDL.Variant({
          'scheduled' : IDL.Null,
          'cancelled' : IDL.Null,
          'completed' : IDL.Null,
          'inProgress' : IDL.Null,
        }),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CarModelInput = IDL.Record({
    'name' : IDL.Text,
    'year' : IDL.Nat,
    'available' : IDL.Bool,
    'category' : IDL.Text,
  });
  const CarModelId = IDL.Nat;
  const DealerLocationInput = IDL.Record({
    'city' : IDL.Text,
    'name' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const DealerLocationId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TestDriveInput = IDL.Record({
    'customerName' : IDL.Text,
    'customerPhone' : IDL.Text,
    'scheduledDate' : IDL.Text,
    'carModelId' : CarModelId,
    'notes' : IDL.Text,
    'dealerLocationId' : DealerLocationId,
  });
  const TestDriveId = IDL.Nat;
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const DashboardStats = IDL.Record({
    'scheduled' : IDL.Nat,
    'total' : IDL.Nat,
    'cancelled' : IDL.Nat,
    'completed' : IDL.Nat,
    'inProgress' : IDL.Nat,
  });
  const CarModel = IDL.Record({
    'id' : CarModelId,
    'name' : IDL.Text,
    'year' : IDL.Nat,
    'available' : IDL.Bool,
    'category' : IDL.Text,
  });
  const DealerLocation = IDL.Record({
    'id' : DealerLocationId,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const TestDrive = IDL.Record({
    'id' : TestDriveId,
    'customerName' : IDL.Text,
    'status' : IDL.Variant({
      'scheduled' : IDL.Null,
      'cancelled' : IDL.Null,
      'completed' : IDL.Null,
      'inProgress' : IDL.Null,
    }),
    'customerPhone' : IDL.Text,
    'scheduledDate' : IDL.Text,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'carModelId' : CarModelId,
    'notes' : IDL.Text,
    'dealerLocationId' : DealerLocationId,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCarModel' : IDL.Func([CarModelInput], [CarModelId], []),
    'addDealerLocation' : IDL.Func(
        [DealerLocationInput],
        [DealerLocationId],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bookTestDrive' : IDL.Func([TestDriveInput], [TestDriveId], []),
    'cancelTestDrive' : IDL.Func([TestDriveId], [], []),
    'deleteCarModel' : IDL.Func([CarModelId], [], []),
    'deleteDealerLocation' : IDL.Func([DealerLocationId], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listCarModels' : IDL.Func([], [IDL.Vec(CarModel)], ['query']),
    'listDealerLocations' : IDL.Func([], [IDL.Vec(DealerLocation)], ['query']),
    'listTestDrives' : IDL.Func([], [IDL.Vec(TestDrive)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'toggleCarModelAvailability' : IDL.Func([CarModelId], [], []),
    'updateTestDriveStatus' : IDL.Func(
        [
          TestDriveId,
          IDL.Variant({
            'scheduled' : IDL.Null,
            'cancelled' : IDL.Null,
            'completed' : IDL.Null,
            'inProgress' : IDL.Null,
          }),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };