/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CarModel {
  'id' : CarModelId,
  'name' : string,
  'color' : string,
  'available' : boolean,
  'category' : string,
}
export type CarModelId = bigint;
export interface CarModelInput {
  'name' : string,
  'color' : string,
  'available' : boolean,
  'category' : string,
}
export interface DashboardStats {
  'scheduled' : bigint,
  'total' : bigint,
  'cancelled' : bigint,
  'completed' : bigint,
  'inProgress' : bigint,
}
export interface DealerLocation {
  'id' : DealerLocationId,
  'city' : string,
  'name' : string,
  'address' : string,
  'phone' : string,
}
export type DealerLocationId = bigint;
export interface DealerLocationInput {
  'city' : string,
  'name' : string,
  'address' : string,
  'phone' : string,
}
export interface TestDrive {
  'id' : TestDriveId,
  'customerName' : string,
  'status' : { 'scheduled' : null } |
    { 'cancelled' : null } |
    { 'completed' : null } |
    { 'inProgress' : null },
  'customerPhone' : string,
  'scheduledDate' : string,
  'userId' : Principal,
  'createdAt' : bigint,
  'carModelId' : CarModelId,
  'notes' : string,
  'dealerLocationId' : DealerLocationId,
}
export type TestDriveId = bigint;
export interface TestDriveInput {
  'customerName' : string,
  'customerPhone' : string,
  'scheduledDate' : string,
  'carModelId' : CarModelId,
  'notes' : string,
  'dealerLocationId' : DealerLocationId,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  /**
   * / -- Car model management --
   */
  'addCarModel' : ActorMethod<[CarModelInput], CarModelId>,
  /**
   * / -- Dealer location management --
   */
  'addDealerLocation' : ActorMethod<[DealerLocationInput], DealerLocationId>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / -- Test drive management --
   */
  'bookTestDrive' : ActorMethod<[TestDriveInput], TestDriveId>,
  'cancelTestDrive' : ActorMethod<[TestDriveId], undefined>,
  'claimSuperAdminByToken' : ActorMethod<[string], boolean>,
  'deleteCarModel' : ActorMethod<[CarModelId], undefined>,
  'deleteDealerLocation' : ActorMethod<[DealerLocationId], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  /**
   * / --- Types ---
   */
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  /**
   * / --- User Profile ---
   */
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listCarModels' : ActorMethod<[], Array<CarModel>>,
  'listDealerLocations' : ActorMethod<[], Array<DealerLocation>>,
  'listTestDrives' : ActorMethod<[], Array<TestDrive>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'toggleCarModelAvailability' : ActorMethod<[CarModelId], undefined>,
  'updateTestDriveStatus' : ActorMethod<
    [
      TestDriveId,
      { 'scheduled' : null } |
        { 'cancelled' : null } |
        { 'completed' : null } |
        { 'inProgress' : null },
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
