/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface DealerLocationInput {
    city: string;
    name: string;
    address: string;
    phone: string;
}
export type CarModelId = bigint;
export interface DealerLocation {
    id: DealerLocationId;
    city: string;
    name: string;
    address: string;
    phone: string;
}
export interface CarModel {
    id: CarModelId;
    name: string;
    color: string;
    available: boolean;
    category: string;
}
export interface CarModelInput {
    name: string;
    color: string;
    available: boolean;
    category: string;
}
export type DealerLocationId = bigint;
export interface TestDrive {
    id: TestDriveId;
    customerName: string;
    status: Variant_scheduled_cancelled_completed_inProgress;
    customerPhone: string;
    scheduledDate: string;
    userId: Principal;
    createdAt: bigint;
    carModelId: CarModelId;
    notes: string;
    dealerLocationId: DealerLocationId;
}
export type TestDriveId = bigint;
export interface TestDriveInput {
    customerName: string;
    customerPhone: string;
    scheduledDate: string;
    carModelId: CarModelId;
    notes: string;
    dealerLocationId: DealerLocationId;
}
export interface UserProfile {
    name: string;
}
export interface DashboardStats {
    scheduled: bigint;
    total: bigint;
    cancelled: bigint;
    completed: bigint;
    inProgress: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_scheduled_cancelled_completed_inProgress {
    scheduled = "scheduled",
    cancelled = "cancelled",
    completed = "completed",
    inProgress = "inProgress"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    /**
     * / -- Car model management --
     */
    addCarModel(input: CarModelInput): Promise<CarModelId>;
    /**
     * / -- Dealer location management --
     */
    addDealerLocation(input: DealerLocationInput): Promise<DealerLocationId>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    /**
     * / -- Test drive management --
     */
    bookTestDrive(input: TestDriveInput): Promise<TestDriveId>;
    cancelTestDrive(testDriveId: TestDriveId): Promise<void>;
    claimSuperAdminByToken(token: string): Promise<boolean>;
    deleteCarModel(carModelId: CarModelId): Promise<void>;
    deleteDealerLocation(dealerLocationId: DealerLocationId): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    /**
     * / --- Types ---
     */
    getCallerUserRole(): Promise<UserRole>;
    getDashboardStats(): Promise<DashboardStats>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    /**
     * / --- User Profile ---
     */
    isCallerAdmin(): Promise<boolean>;
    listCarModels(): Promise<Array<CarModel>>;
    listDealerLocations(): Promise<Array<DealerLocation>>;
    listTestDrives(): Promise<Array<TestDrive>>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    toggleCarModelAvailability(carModelId: CarModelId): Promise<void>;
    updateTestDriveStatus(testDriveId: TestDriveId, newStatus: Variant_scheduled_cancelled_completed_inProgress): Promise<void>;
}
import type { CarModelId as _CarModelId, DealerLocationId as _DealerLocationId, TestDrive as _TestDrive, TestDriveId as _TestDriveId, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCarModel(arg0: CarModelInput): Promise<CarModelId> {
        if (this.processError) {
            try {
                const result = await this.actor.addCarModel(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCarModel(arg0);
            return result;
        }
    }
    async addDealerLocation(arg0: DealerLocationInput): Promise<DealerLocationId> {
        if (this.processError) {
            try {
                const result = await this.actor.addDealerLocation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDealerLocation(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async bookTestDrive(arg0: TestDriveInput): Promise<TestDriveId> {
        if (this.processError) {
            try {
                const result = await this.actor.bookTestDrive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bookTestDrive(arg0);
            return result;
        }
    }
    async cancelTestDrive(arg0: TestDriveId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelTestDrive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelTestDrive(arg0);
            return result;
        }
    }
    async claimSuperAdminByToken(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.claimSuperAdminByToken(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimSuperAdminByToken(arg0);
            return result;
        }
    }
    async deleteCarModel(arg0: CarModelId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCarModel(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCarModel(arg0);
            return result;
        }
    }
    async deleteDealerLocation(arg0: DealerLocationId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDealerLocation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDealerLocation(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listCarModels(): Promise<Array<CarModel>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCarModels();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCarModels();
            return result;
        }
    }
    async listDealerLocations(): Promise<Array<DealerLocation>> {
        if (this.processError) {
            try {
                const result = await this.actor.listDealerLocations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listDealerLocations();
            return result;
        }
    }
    async listTestDrives(): Promise<Array<TestDrive>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTestDrives();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTestDrives();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async toggleCarModelAvailability(arg0: CarModelId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleCarModelAvailability(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleCarModelAvailability(arg0);
            return result;
        }
    }
    async updateTestDriveStatus(arg0: TestDriveId, arg1: Variant_scheduled_cancelled_completed_inProgress): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTestDriveStatus(arg0, to_candid_variant_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTestDriveStatus(arg0, to_candid_variant_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_TestDrive_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TestDrive): TestDrive {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TestDriveId;
    customerName: string;
    status: {
        scheduled: null;
    } | {
        cancelled: null;
    } | {
        completed: null;
    } | {
        inProgress: null;
    };
    customerPhone: string;
    scheduledDate: string;
    userId: Principal;
    createdAt: bigint;
    carModelId: _CarModelId;
    notes: string;
    dealerLocationId: _DealerLocationId;
}): {
    id: TestDriveId;
    customerName: string;
    status: Variant_scheduled_cancelled_completed_inProgress;
    customerPhone: string;
    scheduledDate: string;
    userId: Principal;
    createdAt: bigint;
    carModelId: CarModelId;
    notes: string;
    dealerLocationId: DealerLocationId;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: from_candid_variant_n9(_uploadFile, _downloadFile, value.status),
        customerPhone: value.customerPhone,
        scheduledDate: value.scheduledDate,
        userId: value.userId,
        createdAt: value.createdAt,
        carModelId: value.carModelId,
        notes: value.notes,
        dealerLocationId: value.dealerLocationId
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    scheduled: null;
} | {
    cancelled: null;
} | {
    completed: null;
} | {
    inProgress: null;
}): Variant_scheduled_cancelled_completed_inProgress {
    return "scheduled" in value ? Variant_scheduled_cancelled_completed_inProgress.scheduled : "cancelled" in value ? Variant_scheduled_cancelled_completed_inProgress.cancelled : "completed" in value ? Variant_scheduled_cancelled_completed_inProgress.completed : "inProgress" in value ? Variant_scheduled_cancelled_completed_inProgress.inProgress : value;
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TestDrive>): Array<TestDrive> {
    return value.map((x)=>from_candid_TestDrive_n7(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_scheduled_cancelled_completed_inProgress): {
    scheduled: null;
} | {
    cancelled: null;
} | {
    completed: null;
} | {
    inProgress: null;
} {
    return value == Variant_scheduled_cancelled_completed_inProgress.scheduled ? {
        scheduled: null
    } : value == Variant_scheduled_cancelled_completed_inProgress.cancelled ? {
        cancelled: null
    } : value == Variant_scheduled_cancelled_completed_inProgress.completed ? {
        completed: null
    } : value == Variant_scheduled_cancelled_completed_inProgress.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
